"""Fix hours_worked column in employee_department table and adding employee_start_date

Revision ID: 3e87636f46e4
Revises: 90bfcd0a6c08
Create Date: 2024-10-14 06:40:54.789481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e87636f46e4'
down_revision = '90bfcd0a6c08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_department', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_start_date', sa.Date(), nullable=True))  # Add employee_start_date column

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_department', schema=None) as batch_op:
        batch_op.drop_column('hours_worked')  # Drop hours_worked column
        batch_op.drop_column('employee_start_date')  # Drop employee_start_date column

    # ### end Alembic commands ###
