"""removing user and password authentication attributes in the Employee Table,  in models.

Revision ID: 90bfcd0a6c08
Revises: 83e16c52e37b
Create Date: 2024-10-12 09:19:15.995113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90bfcd0a6c08'
down_revision = '83e16c52e37b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('work_hours',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('user_name')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('user_name', sa.VARCHAR(), nullable=False))
        batch_op.alter_column('work_hours',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
