"""Initial version for GroceryStore, Employee, and Department

Revision ID: c146b5be8b18
Revises: 
Create Date: 2024-10-11 20:38:45.063437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c146b5be8b18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grocery_store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('grocery_store_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grocery_store_id'], ['grocery_store.id'], name=op.f('fk_departments_grocery_store_id_grocery_store')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('work_hours', sa.String(), nullable=True),
    sa.Column('grocery_store_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grocery_store_id'], ['grocery_store.id'], name=op.f('fk_employees_grocery_store_id_grocery_store')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_department',
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_employee_department_department_id_departments')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_department_employee_id_employees'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_department')
    op.drop_table('employees')
    op.drop_table('departments')
    op.drop_table('grocery_store')
    # ### end Alembic commands ###
